### PR TITLE
Fix text extraction from Word templates (dotx)

### PR DESCRIPTION
**Pull request by pdpotter**
The main text content of a Word template file (dotx) is contained in the same file as a regular Word file (docx): (word/document.xml). However, this file has a different content type in the `[Content_Types].xml` file (contained in the dotx zip archive):
```
<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml"/>
```

Because of this, a text extractor with the wrong content type is used during the text indexing of Word templates, which results in the following KeyError:
```
Traceback (most recent call last):
  File ".../openxmllib/openxmllib/document.py", line 212, in indexableText
    for tree in self.content_types.getTreesFor(self, extractor.content_type):
  File ".../openxmllib/openxmllib/contenttypes.py", line 98, in getTreesFor
    for rel_path in self.overrides[content_type]:
KeyError: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml'
```

This pull request addresses this problem by
* adding an extra text extractor for word processing (to process files with content type `application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml`)
* checking if a text extractor corresponds to a content type present in the processed file before using it

Since the text content of Excel and Powerpoint template files (xltx and potx) are not contained in the `main` file, but in the `worksheet` and `slide` files respectively, the text extraction from these template files doesn't cause KeyErrors.

### CODE REVIEW

**Comment by petri** [comment]
Thanks for your effort. It did not even occur to me to use openxmllib with template documents, but sounds good to me. A thumbs-up for providing tests. @glenfant, any thoughts?

**Comment by glenfant** [comment]
@petri and @pdpotter Thanks for the contribution. This sounds good to me too. Let the merge do the job.

**Comment by pdpotter** [comment]
Thanks for the quick review and merge!

When is the next openxmllib release planned?

**Comment by petri** [comment]
released 1.1.1; see PyPI.

**Pull request merged**
